config/routes.rb
Rails.application.routes.draw do
  resources :order_items
  get 'cart', to: 'cart#show'
  devise_for :users

  root to: 'product#list'
  get 'product/show'
  get 'product/new'
  get 'product/create'
  post 'product/create'
  get 'product/edit'
  get 'product/update'
  patch 'product/update'
  get 'product/delete'
  get 'categories/show'
  post 'categories/show'
  get 'product/page'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :order_items
    before_save :set_subtotal

    def subtotal
        order_items.collect{|order_item| order_item.valid? ? order_item.unit_price * order_item.quantity : 0}.sum
    end

    def set_subtotal
        self[:subtotal] = subtotal
    end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order

  before_save :set_unit_price
  before_save :set_total

  def unit_price
    #if there is a record
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total
    return unit_price * quantity
  end

  private
  def set_unit_price
    self[:unit_price] = unit_price
  end

  def set_total
    self[:total] = total * quantity
  end
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :category
    has_many :order_items
    validates_presence_of :title
    validates_numericality_of :price, :message=>"Error Message"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include ApplicationHelper
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def show
    @order_items = current_order.order_items
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])
    @order_item = current_order.order_items.new
  end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController


  def create
      @order = current_order
      @order_item = @order.order_items.new(order_params)
      @order.save
      session[:order_id] = @order.id
  end
  def update
      @order = current_order
      @order_item = @order.order_items.find(params[:id])
      @order_item.update(order_params)
      @order_items = current_order.order_items
  end

  def destroy
      @order = current_order
      @order_item = @order.order_items.find(params[:id])
      @order_item.destroy
      @order_items = current_order.order_items
  end
  private
  def order_params
      params.require(:order_item).permit(:product_id, :quantity)
  end
end

app/controllers/product_controller.rb
class ProductController < ApplicationController
  
  def list
    @products = Product.all
    @order_item = current_order.order_items.new
  end

  def page
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
    @categories = Category.all
  end

  def product_params
    params.require(:products).permit(:title, :price, :category_id, :description)
  end

  def create
    @product = Product.new(product_params)

    if @product.save
       redirect_to :action => 'list'
    else
       @categories = Category.all
       render :action => 'new'
    end
  end
 
  def edit
    @product = Product.find(params[:id])
    @categories = Category.all
  end
 
  def update
    @product = Product.find(params[:id])

    if @product.update(product_param)
        redirect_to :action => 'show', :id => @product
    else
        @categories = Category.all
        render :action => 'edit'
    end
  end

  def product_param
    params.require(:product).permit(:title, :description, :price, :category_id)
  end
 
  def delete
    Product.find(params[:id]).destroy
    redirect_to :action => 'list'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def current_order
      #use find by id to avoid potential errors
      if Order.find_by_id(session[:order_id]).nil?
        Order.new
      else
        Order.find_by_id(session[:order_id])
      end
    end



    def number_to_indian_currency(number)
        if number
          string = number.to_s.split('.')
          number = string[0].gsub(/(\d+)(\d{3})$/){ p = $2;"#{$1.reverse.gsub(/(\d{2})/,'\1,').reverse},#{p}"}
          number = number.gsub(/^,/, '') + '.' + string[1] if string[1]
          # remove leading comma
          number = number[1..-1] if number[0] == 44
        end
        "Rs. #{number}"
      end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/views/cart/_cart.html.erb
<%= link_to "#{current_order.order_items.size} items with a value of #{number_to_indian_currency(current_order.subtotal)}", cart_path %>

app/views/cart/_cart_items.html.erb
<% @order_items.each do |item| %>
    <h3><%= item.product.title %></h3>
    <h3><%= number_to_indian_currency(item.product.price) %></h3>
    <%= form_with model: item do |f| %>
        <%= f.hidden_field :product_id, value: item.product.id %>
        <%= f.number_field :quantity, value: item.quantity.to_i %>
        <%= f.submit "Update Cart" %>
        <%= link_to "Remove Item", item, method: :delete, remote: true %>
    <% end %>
<h2> Subtotal: <%= number_to_indian_currency(item.total) %> </h2>
<% end %>

<h3>Your current order has a total of: <%= number_to_indian_currency(current_order.subtotal) %></h3>

app/views/cart/show.html.erb
<div id="cart-item">
    <%= render 'cart_items' %>

</div>

app/views/categories/show.html.erb
<h1><%= @category.name -%></h1>

<ul>
   <% @category.products.each do |c| %>
   <%# <li><%= link_to c.title, :action => "show", :controller => 'product', :id => c.id -%>
  <li><%= c.title %>
   <%= form_with model: @order_item, remote: true do |f| %>
      <%= f.hidden_field :product_id, value: c.id %>
      <%= f.number_field :quantity, value: 1, min: 1%>
      <%= f.submit "Add To Cart" %>
   <%end%>
  
  </li>
  
   <% end %>
</ul>

<h3><%= render 'cart/cart' %></h3>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
      <% if user_signed_in? %>
       
        <li class="nav-item">
          <%= link_to 'Page', product_page_path, class: 'nav-link', style: 'display:none' %>
        </li>
       
        <li class="nav-item">
          <%= link_to "Home", root_path, class: 'nav-link' %>
        </li>
          <li class="nav-item">
          <%= link_to 'Cart', cart_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
        </li>
        <% else %>
        <li class="nav-item">
          <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link' %>
        </li>
       <li class="nav-item">
          <%= link_to 'Sign In', new_user_session_path, class: 'nav-link' %>
        </li>
        <% end %>
      
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShopCart</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/navbar' %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/order_items/create.js.erb
$("#cart").html("<%= j render 'cart/cart' %>");

app/views/order_items/destroy.js.erb
$("#cart").html("<%= j render 'cart/cart' %>");
$("#cart-item").html("<%= j render 'cart/cart_items' %>");

app/views/order_items/update.js.erb
$("#cart").html("<%= j render 'cart/cart' %>");
$("#cart-item").html("<%= j render 'cart/cart_items' %>");

app/views/product/create.html.erb
<h1>Product#create</h1>
<p>Find me in app/views/product/create.html.erb</p>

app/views/product/delete.html.erb
<h1>Product#delete</h1>
<p>Find me in app/views/product/delete.html.erb</p>

app/views/product/edit.html.erb
<h1>Edit Product Detail</h1>

<%= form_for @product, :url =>{:action => "update", :id =>@product} do |f| %>

<p>Title: <%= f.text_field 'title' %></p>
<p>Price: <%= f.text_field  'price' %></p>
<p>Category: <%= f.collection_select :category_id, Category.all, :id, :name %></p>
<p>Description<br/>

<%= f.text_area 'description' %></p>
<%= f.submit "Save changes" %>
<% end %>

<%= link_to 'Back', {:action => 'list' } %>

app/views/product/list.html.erb
<h2> Categories </h2>


<ol id = "categories"> 

   <% Category.all.each do |c| %>
   <li><button type="button"><%= link_to c.name, :action => "show", :controller => 'categories', :id => c.id %></button></li>
   <% end %>
   
</ol>

app/views/product/new.html.erb
<h1>Add new Product</h1>

<%= form_tag :action => 'create' do %>

<p><label for = "product_title", class="col-sm-2 col-form-label col-form-label-sm">Title</label>:
<%= text_field 'products', 'title', :class => "col-sm-2" %></p>

<p><label for = "product_price", class="col-sm-2 col-form-label col-form-label-sm">Price</label>:
<%= text_field 'products', 'price', :class => "col-sm-2" %></p>

<p><label for = "product_category_id", class="col-sm-2 col-form-label col-form-label-sm">Category</label>:
<%= collection_select(:products, :category_id, @categories, :id, :name, prompt: true) %></p>

<p><label for = "product_description", class="col-sm-2 col-form-label col-form-label-sm">Description</label>:
<%= text_area 'products', 'description' %></p>

<%= submit_tag "Create", class: "btn btn-primary" %>

<% end -%>
<br/>

<%= link_to 'Back', {:action => 'list'}, class: "btn btn-info "%>

app/views/product/page.html.erb
<% if @products.blank? %>
<p>There are not any products currently in the system.</p>
<% else %>
<table class="table table-bordered border-primary">
   <thead>
      <tr>
         <th scope="col"> Products </th>
         <th scope="col"> Price </th>
         <th scope="col"> Edit </th>
         <th scope="col"> Delete </th>
      </tr>
   </thead>
   <tbody>
   <% @products.each do |product| %>
      <tr>
         
         <td> <%= product.title%> </td>
         <td> <%= number_to_indian_currency(product.price) %> </td>
         <td><%= link_to 'Edit', {:action => 'edit', :id => product.id} %></td>
         <td><%= link_to "Delete", {:action => 'delete', :id => product.id},
      :confirm => "Are you sure you want to delete this item?" %></td>
         
      </tr>
      <% end %>
   </tbody>
</table>
<% end %>
<p><%= link_to "Add new Product", {:action => 'new' }, class: 'btn btn-danger' %></p>

app/views/product/show.html.erb
<h1><%= @product.title %></h1>

<p>
   <strong>Price: </strong> $<%= @product.price %><br />
   <strong>Category :</strong><%= link_to @product.category.name,
   :action => "show", :controller => 'product', :id => @product.category.id %><br />
   <strong>Created Date:</strong> <%= @product.created_at %><br />
</p>

<p><%= @product.description %></p>

<hr />

<%= link_to 'Back', {:action => 'list'} %>

app/views/product/update.html.erb
<h1>Product#update</h1>
<p>Find me in app/views/product/update.html.erb</p>